### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by alikrc** [Hydrosis/Exception-Formatter#1]
Not working in current status

**Comment by RadwanFaci** [comment]
What issue are you running into?

**Comment by alikrc** [comment]
Hi,

i installed the plugin, without saving the file, Ctrl+Shift+P then Format Stack Trace command. It didn't work at the last version of vs code.

**Comment by RadwanFaci** [comment]
Can you provide the stack trace you're trying to format?

**Comment by alikrc** [comment]
Sorry i didn't save it so i can't. Next time I'll try again
